# Site settings
title: Dindoléon !
email: simon.deplat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hahahahahahaha !!!
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: ElUerdo
github_username:  sdeplat

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  dessin:
    output: true
    permalink: /dessin/:path/
  musique:
    output: true
    permalink: /musique/:path/
